<?php
/**
 * This file is generated by the "yii asset" command.
 * DO NOT MODIFY THIS FILE DIRECTLY.
 * @version 2018-03-02 03:23:08
 */
return [
    'addfood' => [
        'class' => 'yii\\web\\AssetBundle',
        'basePath' => '@webroot/assets',
        'baseUrl' => '@web/assets',
        'js' => [
            'js/addfood-d8b9235ec6d5c34fc2ec70b64ed2a5f3.js',
        ],
        'css' => [
            'css/addfood-063bb2804492002da254c35864d0fa9c.css',
        ],
        'depends' => [],
        'sourcePath' => null,
    ],
    'addstaff' => [
        'class' => 'yii\\web\\AssetBundle',
        'basePath' => '@webroot/assets',
        'baseUrl' => '@web/assets',
        'js' => [],
        'css' => [
            'css/addstaff-cb029b88e50ce00ba12e8cba1acdfaa0.css',
        ],
        'depends' => [],
        'sourcePath' => null,
    ],
    'site' => [
        'class' => 'yii\\web\\AssetBundle',
        'basePath' => '@webroot/assets',
        'baseUrl' => '@web/assets',
        'js' => [
            'js/site-1b6f0cedeb064946d90b0e80182bebfe.js',
        ],
        'css' => [
            'css/site-ca669df12bd69f2d1c0b65fadae3b399.css',
        ],
        'depends' => [],
        'sourcePath' => null,
    ],
    'cart' => [
        'class' => 'yii\\web\\AssetBundle',
        'basePath' => '@webroot/assets',
        'baseUrl' => '@web/assets',
        'js' => [
            'js/cart-bbe2f3c90760ffe27e8e531e09fce12b.js',
        ],
        'css' => [
            'css/cart-ce69294870ad016ed6751ddecb73003f.css',
        ],
        'depends' => [],
        'sourcePath' => null,
    ],
    'comment' => [
        'class' => 'yii\\web\\AssetBundle',
        'basePath' => '@webroot/assets',
        'baseUrl' => '@web/assets',
        'js' => [],
        'css' => [
            'css/comment-2a1183d2898305a453133bb54386088e.css',
        ],
        'depends' => [],
        'sourcePath' => null,
    ],
    'cooking' => [
        'class' => 'yii\\web\\AssetBundle',
        'basePath' => '@webroot/assets',
        'baseUrl' => '@web/assets',
        'js' => [
            'js/cooking-e6134e476784294b3f7f854d7dc4169e.js',
        ],
        'css' => [
            'css/cooking-b65eadb1b617a714769deb99d79e3036.css',
        ],
        'depends' => [],
        'sourcePath' => null,
    ],
    'deliverylocation' => [
        'class' => 'yii\\web\\AssetBundle',
        'basePath' => '@webroot/assets',
        'baseUrl' => '@web/assets',
        'js' => [],
        'css' => [
            'css/deliverylocation-6de46e3a5e3176510dbaa94c073764cd.css',
        ],
        'depends' => [],
        'sourcePath' => null,
    ],
    'deliveryorder' => [
        'class' => 'yii\\web\\AssetBundle',
        'basePath' => '@webroot/assets',
        'baseUrl' => '@web/assets',
        'js' => [
            'js/deliveryorder-36fd7b71943dd0bd81703eedf6eaaae3.js',
        ],
        'css' => [
            'css/deliveryorder-0f36fda06654289ac1d2625a83933e94.css',
        ],
        'depends' => [],
        'sourcePath' => null,
    ],
    'deliveryorderhistory' => [
        'class' => 'yii\\web\\AssetBundle',
        'basePath' => '@webroot/assets',
        'baseUrl' => '@web/assets',
        'js' => [],
        'css' => [
            'css/deliveryorderhistory-389882356bc568abbfc3c3585988cdfa.css',
        ],
        'depends' => [],
        'sourcePath' => null,
    ],
    'editrestaurant' => [
        'class' => 'yii\\web\\AssetBundle',
        'basePath' => '@webroot/assets',
        'baseUrl' => '@web/assets',
        'js' => [
            'js/editrestaurant-54717d44c4994048cd4545105565752f.js',
        ],
        'css' => [
            'css/editrestaurant-7082b870cace543b700fed9df05a8aef.css',
        ],
        'depends' => [],
        'sourcePath' => null,
    ],
    'feedback' => [
        'class' => 'yii\\web\\AssetBundle',
        'basePath' => '@webroot/assets',
        'baseUrl' => '@web/assets',
        'js' => [],
        'css' => [
            'css/feedback-6bf02b5e96e8ea4d325c50c7bde3a72a.css',
        ],
        'depends' => [],
        'sourcePath' => null,
    ],
    'food' => [
        'class' => 'yii\\web\\AssetBundle',
        'basePath' => '@webroot/assets',
        'baseUrl' => '@web/assets',
        'js' => [
            'js/food-e23603857e0429bf30f6a6083be90a9b.js',
        ],
        'css' => [
            'css/food-57352a0d4bfd5e062f46acb163a7528f.css',
        ],
        'depends' => [],
        'sourcePath' => null,
    ],
    'menu' => [
        'class' => 'yii\\web\\AssetBundle',
        'basePath' => '@webroot/assets',
        'baseUrl' => '@web/assets',
        'js' => [
            'js/menu-2506b19c5d4e25d56a65ba130aead08c.js',
        ],
        'css' => [
            'css/menu-303f140e7e90be59b1703d7cae8cb7e0.css',
        ],
        'depends' => [],
        'sourcePath' => null,
    ],
    'fonoff' => [
        'class' => 'yii\\web\\AssetBundle',
        'basePath' => '@webroot/assets',
        'baseUrl' => '@web/assets',
        'js' => [],
        'css' => [
            'css/fonoff-320b53b5b30bda621dc0cce7f2927d4c.css',
        ],
        'depends' => [],
        'sourcePath' => null,
    ],
    'fservice' => [
        'class' => 'yii\\web\\AssetBundle',
        'basePath' => '@webroot/assets',
        'baseUrl' => '@web/assets',
        'js' => [],
        'css' => [
            'css/fservice-41cad74c2d4c2bf6854d0798f6b076b7.css',
        ],
        'depends' => [],
        'sourcePath' => null,
    ],
    'staff' => [
        'class' => 'yii\\web\\AssetBundle',
        'basePath' => '@webroot/assets',
        'baseUrl' => '@web/assets',
        'js' => [],
        'css' => [
            'css/staff-a2bb33e15595c88581dd3eae1f46e80e.css',
        ],
        'depends' => [],
        'sourcePath' => null,
    ],
    'myorder' => [
        'class' => 'yii\\web\\AssetBundle',
        'basePath' => '@webroot/assets',
        'baseUrl' => '@web/assets',
        'js' => [],
        'css' => [
            'css/myorder-490225660f3e1cc26953dae5d1353e2f.css',
        ],
        'depends' => [],
        'sourcePath' => null,
    ],
    'myorderhs' => [
        'class' => 'yii\\web\\AssetBundle',
        'basePath' => '@webroot/assets',
        'baseUrl' => '@web/assets',
        'js' => [],
        'css' => [
            'css/myorderhs-56a7ed238c77df312cc5bee7d2ff767a.css',
        ],
        'depends' => [],
        'sourcePath' => null,
    ],
    'voucher' => [
        'class' => 'yii\\web\\AssetBundle',
        'basePath' => '@webroot/assets',
        'baseUrl' => '@web/assets',
        'js' => [],
        'css' => [
            'css/voucher-9d33899aa5780b9f70ee59f02cf18ef7.css',
        ],
        'depends' => [],
        'sourcePath' => null,
    ],
    'newres' => [
        'class' => 'yii\\web\\AssetBundle',
        'basePath' => '@webroot/assets',
        'baseUrl' => '@web/assets',
        'js' => [],
        'css' => [
            'css/newres-1693994296f49439e71bed887626911f.css',
        ],
        'depends' => [],
        'sourcePath' => null,
    ],
    'news' => [
        'class' => 'yii\\web\\AssetBundle',
        'basePath' => '@webroot/assets',
        'baseUrl' => '@web/assets',
        'js' => [],
        'css' => [
            'css/news-f224e877bec1a57b9de07d9e3ebdb9b1.css',
        ],
        'depends' => [],
        'sourcePath' => null,
    ],
    'notic' => [
        'class' => 'yii\\web\\AssetBundle',
        'basePath' => '@webroot/assets',
        'baseUrl' => '@web/assets',
        'js' => [],
        'css' => [
            'css/notic-13dc484a29bab93657c88cf40bd3de00.css',
        ],
        'depends' => [],
        'sourcePath' => null,
    ],
    'orderdetail' => [
        'class' => 'yii\\web\\AssetBundle',
        'basePath' => '@webroot/assets',
        'baseUrl' => '@web/assets',
        'js' => [],
        'css' => [
            'css/orderdetail-423641d5c1d5ba0be79e077bd8e8b1f8.css',
        ],
        'depends' => [],
        'sourcePath' => null,
    ],
    'payment' => [
        'class' => 'yii\\web\\AssetBundle',
        'basePath' => '@webroot/assets',
        'baseUrl' => '@web/assets',
        'js' => [],
        'css' => [
            'css/payment-c0f2696d311a56abe7a11257321982f9.css',
        ],
        'depends' => [],
        'sourcePath' => null,
    ],
    'slider' => [
        'class' => 'yii\\web\\AssetBundle',
        'basePath' => '@webroot/assets',
        'baseUrl' => '@web/assets',
        'js' => [
            'js/slider-d064a4d498efcae28d98527e635b8901.js',
        ],
        'css' => [
            'css/slider-8330dbdc80f5cc9c1ffda26b00c1826e.css',
        ],
        'depends' => [],
        'sourcePath' => null,
    ],
    'rating' => [
        'class' => 'yii\\web\\AssetBundle',
        'basePath' => '@webroot/assets',
        'baseUrl' => '@web/assets',
        'js' => [
            'js/rating-577b25c451831021d1d8b6a9ac97a4d3.js',
        ],
        'css' => [
            'css/rating-595eb2ce9abdad018274210bc830ee2d.css',
        ],
        'depends' => [],
        'sourcePath' => null,
    ],
    'resdetail2' => [
        'class' => 'yii\\web\\AssetBundle',
        'basePath' => '@webroot/assets',
        'baseUrl' => '@web/assets',
        'js' => [
            'js/resdetail2-5c1ca251776ffb1f1443b103c10866ed.js',
        ],
        'css' => [
            'css/resdetail2-afb8271d1227489650bc6ae73dd32d3c.css',
        ],
        'depends' => [],
        'sourcePath' => null,
    ],
    'resdetail1' => [
        'class' => 'yii\\web\\AssetBundle',
        'basePath' => '@webroot/assets',
        'baseUrl' => '@web/assets',
        'js' => [
            'js/resdetail1-405147cd4bc38e68f5b82925afb03795.js',
        ],
        'css' => [
            'css/resdetail1-7c63bbbb3207dbc97ffebd684de08eee.css',
        ],
        'depends' => [],
        'sourcePath' => null,
    ],
    'resdetail' => [
        'class' => 'yii\\web\\AssetBundle',
        'basePath' => '@webroot/assets',
        'baseUrl' => '@web/assets',
        'js' => [
            'js/resdetail-92a39c8e8b89d5b6debf67aab8168eab.js',
        ],
        'css' => [
            'css/resdetail-b7e0154616f637672e6dd896018c8c75.css',
        ],
        'depends' => [],
        'sourcePath' => null,
    ],
    'earning' => [
        'class' => 'yii\\web\\AssetBundle',
        'basePath' => '@webroot/assets',
        'baseUrl' => '@web/assets',
        'js' => [],
        'css' => [
            'css/earning-d108988695aad7ddd4b3332d874f1375.css',
        ],
        'depends' => [],
        'sourcePath' => null,
    ],
    'resorder' => [
        'class' => 'yii\\web\\AssetBundle',
        'basePath' => '@webroot/assets',
        'baseUrl' => '@web/assets',
        'js' => [
            'js/resorder-32b04bbd18408a7c648f40e79f5b5133.js',
        ],
        'css' => [
            'css/resorder-8affbbfdbe55fd09b2f9c2b9ea2a2f1a.css',
        ],
        'depends' => [],
        'sourcePath' => null,
    ],
    'resorderhis' => [
        'class' => 'yii\\web\\AssetBundle',
        'basePath' => '@webroot/assets',
        'baseUrl' => '@web/assets',
        'js' => [
            'js/resorderhis-b89377d24b6e4e64cba6509bd4da1626.js',
        ],
        'css' => [
            'css/resorderhis-2a319009061f880b705ad9d0e82b9369.css',
        ],
        'depends' => [],
        'sourcePath' => null,
    ],
    'resorderserv' => [
        'class' => 'yii\\web\\AssetBundle',
        'basePath' => '@webroot/assets',
        'baseUrl' => '@web/assets',
        'js' => [],
        'css' => [
            'css/resorderserv-4819942609e9448374a6aef3391b9903.css',
        ],
        'depends' => [],
        'sourcePath' => null,
    ],
    'statis' => [
        'class' => 'yii\\web\\AssetBundle',
        'basePath' => '@webroot/assets',
        'baseUrl' => '@web/assets',
        'js' => [],
        'css' => [
            'css/statis-52a011b24b997d7e6c3991b395762eb4.css',
        ],
        'depends' => [],
        'sourcePath' => null,
    ],
    'star' => [
        'class' => 'yii\\web\\AssetBundle',
        'basePath' => '@webroot/assets',
        'baseUrl' => '@web/assets',
        'js' => [
            'js/star-8a9b33ea145a21af484270cc23eb3425.js',
        ],
        'css' => [
            'css/star-9494bd9bd49af23335421a127bcd9781.css',
        ],
        'depends' => [],
        'sourcePath' => null,
    ],
    'topup' => [
        'class' => 'yii\\web\\AssetBundle',
        'basePath' => '@webroot/assets',
        'baseUrl' => '@web/assets',
        'js' => [],
        'css' => [
            'css/topup-2dbeed43dd979a92590c83367e71b82b.css',
        ],
        'depends' => [],
        'sourcePath' => null,
    ],
    'accounthistory' => [
        'class' => 'yii\\web\\AssetBundle',
        'basePath' => '@webroot/assets',
        'baseUrl' => '@web/assets',
        'js' => [],
        'css' => [
            'css/accounthistory-11ab033fa8958b9cbd9b3bf10a889985.css',
        ],
        'depends' => [],
        'sourcePath' => null,
    ],
    'user' => [
        'class' => 'yii\\web\\AssetBundle',
        'basePath' => '@webroot/assets',
        'baseUrl' => '@web/assets',
        'js' => [
            'js/user-05f5ea0685c8414d80d758c8e326c6d7.js',
        ],
        'css' => [
            'css/user-55831ea9778b18ee47ea7e1cc8d43652.css',
        ],
        'depends' => [],
        'sourcePath' => null,
    ],
    'viewres' => [
        'class' => 'yii\\web\\AssetBundle',
        'basePath' => '@webroot/assets',
        'baseUrl' => '@web/assets',
        'js' => [],
        'css' => [
            'css/viewres-72365c2b451bf3958776091e62e318f9.css',
        ],
        'depends' => [],
        'sourcePath' => null,
    ],
    'all' => [
        'class' => 'yii\\web\\AssetBundle',
        'basePath' => '@webroot/assets',
        'baseUrl' => '@web/assets',
        'js' => [
            'js/all-f06a824735a0c51a77d2eceaf4ed765c.js',
        ],
        'css' => [
            'css/all-55e736c3910bf717bff83f69a9b8a860.css',
        ],
        'sourcePath' => null,
        'depends' => [],
    ],
    'frontend\\assets\\AddFoodAsset' => [
        'sourcePath' => null,
        'js' => [],
        'css' => [],
        'depends' => [
            'yii\\web\\YiiAsset',
            'yii\\bootstrap\\BootstrapAsset',
            'iutbay\\yii2fontawesome\\FontAwesomeAsset',
            'addfood',
        ],
    ],
    'frontend\\assets\\AddStaffAsset' => [
        'sourcePath' => null,
        'js' => [],
        'css' => [],
        'depends' => [
            'yii\\web\\YiiAsset',
            'yii\\bootstrap\\BootstrapAsset',
            'iutbay\\yii2fontawesome\\FontAwesomeAsset',
            'addstaff',
        ],
    ],
    'frontend\\assets\\AppAsset' => [
        'sourcePath' => null,
        'js' => [],
        'css' => [],
        'depends' => [
            'yii\\web\\YiiAsset',
            'yii\\bootstrap\\BootstrapAsset',
            'iutbay\\yii2fontawesome\\FontAwesomeAsset',
            'site',
        ],
    ],
    'frontend\\assets\\CartAsset' => [
        'sourcePath' => null,
        'js' => [],
        'css' => [],
        'depends' => [
            'yii\\web\\YiiAsset',
            'yii\\bootstrap\\BootstrapAsset',
            'iutbay\\yii2fontawesome\\FontAwesomeAsset',
            'cart',
        ],
    ],
    'frontend\\assets\\CheckoutAsset' => [
        'sourcePath' => null,
        'js' => [],
        'css' => [],
        'depends' => [
            'yii\\web\\YiiAsset',
            'yii\\bootstrap\\BootstrapAsset',
            'iutbay\\yii2fontawesome\\FontAwesomeAsset',
            'cart',
        ],
    ],
    'frontend\\assets\\CommentsAsset' => [
        'sourcePath' => null,
        'js' => [],
        'css' => [],
        'depends' => [
            'yii\\web\\YiiAsset',
            'yii\\bootstrap\\BootstrapAsset',
            'iutbay\\yii2fontawesome\\FontAwesomeAsset',
            'comment',
        ],
    ],
    'frontend\\assets\\CookingAsset' => [
        'sourcePath' => null,
        'js' => [],
        'css' => [],
        'depends' => [
            'yii\\web\\YiiAsset',
            'yii\\bootstrap\\BootstrapAsset',
            'iutbay\\yii2fontawesome\\FontAwesomeAsset',
            'cooking',
        ],
    ],
    'frontend\\assets\\DeliveryLocationAsset' => [
        'sourcePath' => null,
        'js' => [],
        'css' => [],
        'depends' => [
            'yii\\web\\YiiAsset',
            'yii\\bootstrap\\BootstrapAsset',
            'iutbay\\yii2fontawesome\\FontAwesomeAsset',
            'deliverylocation',
        ],
    ],
    'frontend\\assets\\DeliverymanOrdersAsset' => [
        'sourcePath' => null,
        'js' => [],
        'css' => [],
        'depends' => [
            'yii\\web\\YiiAsset',
            'yii\\bootstrap\\BootstrapAsset',
            'iutbay\\yii2fontawesome\\FontAwesomeAsset',
            'deliveryorder',
        ],
    ],
    'frontend\\assets\\DeliverymanOrdersHistoryAsset' => [
        'sourcePath' => null,
        'js' => [],
        'css' => [],
        'depends' => [
            'yii\\web\\YiiAsset',
            'yii\\bootstrap\\BootstrapAsset',
            'iutbay\\yii2fontawesome\\FontAwesomeAsset',
            'deliveryorderhistory',
        ],
    ],
    'frontend\\assets\\EditRestaurantDetailsAsset' => [
        'sourcePath' => null,
        'js' => [],
        'css' => [],
        'depends' => [
            'yii\\web\\YiiAsset',
            'yii\\bootstrap\\BootstrapAsset',
            'iutbay\\yii2fontawesome\\FontAwesomeAsset',
            'editrestaurant',
        ],
    ],
    'frontend\\assets\\FeedbackAsset' => [
        'sourcePath' => null,
        'js' => [],
        'css' => [],
        'depends' => [
            'yii\\web\\YiiAsset',
            'yii\\bootstrap\\BootstrapAsset',
            'iutbay\\yii2fontawesome\\FontAwesomeAsset',
            'feedback',
        ],
    ],
    'frontend\\assets\\FoodDetailsAsset' => [
        'sourcePath' => null,
        'js' => [],
        'css' => [],
        'depends' => [
            'yii\\web\\YiiAsset',
            'yii\\bootstrap\\BootstrapAsset',
            'iutbay\\yii2fontawesome\\FontAwesomeAsset',
            'food',
        ],
    ],
    'frontend\\assets\\FoodMenuAsset' => [
        'sourcePath' => null,
        'js' => [],
        'css' => [],
        'depends' => [
            'yii\\web\\YiiAsset',
            'yii\\bootstrap\\BootstrapAsset',
            'iutbay\\yii2fontawesome\\FontAwesomeAsset',
            'menu',
        ],
    ],
    'frontend\\assets\\FoodOnOffAsset' => [
        'sourcePath' => null,
        'js' => [],
        'css' => [],
        'depends' => [
            'yii\\web\\YiiAsset',
            'yii\\bootstrap\\BootstrapAsset',
            'iutbay\\yii2fontawesome\\FontAwesomeAsset',
            'fonoff',
        ],
    ],
    'frontend\\assets\\FoodServiceAsset' => [
        'sourcePath' => null,
        'js' => [],
        'css' => [],
        'depends' => [
            'yii\\web\\YiiAsset',
            'yii\\bootstrap\\BootstrapAsset',
            'iutbay\\yii2fontawesome\\FontAwesomeAsset',
            'fservice',
        ],
    ],
    'frontend\\assets\\ManageStaffAsset' => [
        'sourcePath' => null,
        'js' => [],
        'css' => [],
        'depends' => [
            'yii\\web\\YiiAsset',
            'yii\\bootstrap\\BootstrapAsset',
            'iutbay\\yii2fontawesome\\FontAwesomeAsset',
            'staff',
        ],
    ],
    'frontend\\assets\\MyOrdersAsset' => [
        'sourcePath' => null,
        'js' => [],
        'css' => [],
        'depends' => [
            'yii\\web\\YiiAsset',
            'yii\\bootstrap\\BootstrapAsset',
            'iutbay\\yii2fontawesome\\FontAwesomeAsset',
            'myorder',
        ],
    ],
    'frontend\\assets\\MyOrdersHistoryAsset' => [
        'sourcePath' => null,
        'js' => [],
        'css' => [],
        'depends' => [
            'yii\\web\\YiiAsset',
            'yii\\bootstrap\\BootstrapAsset',
            'iutbay\\yii2fontawesome\\FontAwesomeAsset',
            'myorderhs',
        ],
    ],
    'frontend\\assets\\MyVouchersAsset' => [
        'sourcePath' => null,
        'js' => [],
        'css' => [],
        'depends' => [
            'yii\\web\\YiiAsset',
            'yii\\bootstrap\\BootstrapAsset',
            'iutbay\\yii2fontawesome\\FontAwesomeAsset',
            'voucher',
        ],
    ],
    'frontend\\assets\\NewRestaurantAsset' => [
        'sourcePath' => null,
        'js' => [],
        'css' => [],
        'depends' => [
            'yii\\web\\YiiAsset',
            'yii\\bootstrap\\BootstrapAsset',
            'iutbay\\yii2fontawesome\\FontAwesomeAsset',
            'newres',
        ],
    ],
    'frontend\\assets\\NewsAsset' => [
        'sourcePath' => null,
        'js' => [],
        'css' => [],
        'depends' => [
            'yii\\web\\YiiAsset',
            'yii\\bootstrap\\BootstrapAsset',
            'iutbay\\yii2fontawesome\\FontAwesomeAsset',
            'news',
        ],
    ],
    'frontend\\assets\\NotificationAsset' => [
        'sourcePath' => null,
        'js' => [],
        'css' => [],
        'depends' => [
            'yii\\web\\YiiAsset',
            'yii\\bootstrap\\BootstrapAsset',
            'iutbay\\yii2fontawesome\\FontAwesomeAsset',
            'notic',
        ],
    ],
    'frontend\\assets\\OrderDetailsAsset' => [
        'sourcePath' => null,
        'js' => [],
        'css' => [],
        'depends' => [
            'yii\\web\\YiiAsset',
            'yii\\bootstrap\\BootstrapAsset',
            'iutbay\\yii2fontawesome\\FontAwesomeAsset',
            'orderdetail',
        ],
    ],
    'frontend\\assets\\PaymentAsset' => [
        'sourcePath' => null,
        'js' => [],
        'css' => [],
        'depends' => [
            'yii\\web\\YiiAsset',
            'yii\\bootstrap\\BootstrapAsset',
            'iutbay\\yii2fontawesome\\FontAwesomeAsset',
            'payment',
        ],
    ],
    'frontend\\assets\\PhotoSliderAsset' => [
        'sourcePath' => null,
        'js' => [],
        'css' => [],
        'depends' => [
            'yii\\web\\YiiAsset',
            'yii\\bootstrap\\BootstrapAsset',
            'iutbay\\yii2fontawesome\\FontAwesomeAsset',
            'slider',
        ],
    ],
    'frontend\\assets\\RatingIndexAsset' => [
        'sourcePath' => null,
        'js' => [],
        'css' => [],
        'depends' => [
            'yii\\web\\YiiAsset',
            'yii\\bootstrap\\BootstrapAsset',
            'iutbay\\yii2fontawesome\\FontAwesomeAsset',
            'rating',
        ],
    ],
    'frontend\\assets\\RestaurantDefaultIndex2Asset' => [
        'sourcePath' => null,
        'js' => [],
        'css' => [],
        'depends' => [
            'yii\\web\\YiiAsset',
            'yii\\bootstrap\\BootstrapAsset',
            'iutbay\\yii2fontawesome\\FontAwesomeAsset',
            'resdetail2',
        ],
    ],
    'frontend\\assets\\RestaurantDefaultIndexAsset' => [
        'sourcePath' => null,
        'js' => [],
        'css' => [],
        'depends' => [
            'yii\\web\\YiiAsset',
            'yii\\bootstrap\\BootstrapAsset',
            'iutbay\\yii2fontawesome\\FontAwesomeAsset',
            'resdetail1',
        ],
    ],
    'frontend\\assets\\RestaurantDetailsAsset' => [
        'sourcePath' => null,
        'js' => [],
        'css' => [],
        'depends' => [
            'yii\\web\\YiiAsset',
            'yii\\bootstrap\\BootstrapAsset',
            'iutbay\\yii2fontawesome\\FontAwesomeAsset',
            'resdetail',
        ],
    ],
    'frontend\\assets\\RestaurantEarningsAsset' => [
        'sourcePath' => null,
        'js' => [],
        'css' => [],
        'depends' => [
            'yii\\web\\YiiAsset',
            'yii\\bootstrap\\BootstrapAsset',
            'iutbay\\yii2fontawesome\\FontAwesomeAsset',
            'earning',
        ],
    ],
    'frontend\\assets\\RestaurantOrdersAsset' => [
        'sourcePath' => null,
        'js' => [],
        'css' => [],
        'depends' => [
            'yii\\web\\YiiAsset',
            'yii\\bootstrap\\BootstrapAsset',
            'iutbay\\yii2fontawesome\\FontAwesomeAsset',
            'resorder',
        ],
    ],
    'frontend\\assets\\RestaurantOrdersHistoryAsset' => [
        'sourcePath' => null,
        'js' => [],
        'css' => [],
        'depends' => [
            'yii\\web\\YiiAsset',
            'yii\\bootstrap\\BootstrapAsset',
            'iutbay\\yii2fontawesome\\FontAwesomeAsset',
            'resorderhis',
        ],
    ],
    'frontend\\assets\\RestaurantServiceAsset' => [
        'sourcePath' => null,
        'js' => [],
        'css' => [],
        'depends' => [
            'yii\\web\\YiiAsset',
            'yii\\bootstrap\\BootstrapAsset',
            'iutbay\\yii2fontawesome\\FontAwesomeAsset',
            'resorderserv',
        ],
    ],
    'frontend\\assets\\RestaurantStatisticsAsset' => [
        'sourcePath' => null,
        'js' => [],
        'css' => [],
        'depends' => [
            'yii\\web\\YiiAsset',
            'yii\\bootstrap\\BootstrapAsset',
            'iutbay\\yii2fontawesome\\FontAwesomeAsset',
            'statis',
        ],
    ],
    'frontend\\assets\\StarsAsset' => [
        'sourcePath' => null,
        'js' => [],
        'css' => [],
        'depends' => [
            'yii\\web\\YiiAsset',
            'yii\\bootstrap\\BootstrapAsset',
            'iutbay\\yii2fontawesome\\FontAwesomeAsset',
            'star',
        ],
    ],
    'frontend\\assets\\TopupIndexAsset' => [
        'sourcePath' => null,
        'js' => [],
        'css' => [],
        'depends' => [
            'yii\\web\\YiiAsset',
            'yii\\bootstrap\\BootstrapAsset',
            'iutbay\\yii2fontawesome\\FontAwesomeAsset',
            'topup',
        ],
    ],
    'frontend\\assets\\TopupWithdrawMpHistoryAsset' => [
        'sourcePath' => null,
        'js' => [],
        'css' => [],
        'depends' => [
            'yii\\web\\YiiAsset',
            'yii\\bootstrap\\BootstrapAsset',
            'iutbay\\yii2fontawesome\\FontAwesomeAsset',
            'accounthistory',
        ],
    ],
    'frontend\\assets\\UserAsset' => [
        'sourcePath' => null,
        'js' => [],
        'css' => [],
        'depends' => [
            'yii\\web\\YiiAsset',
            'yii\\bootstrap\\BootstrapAsset',
            'iutbay\\yii2fontawesome\\FontAwesomeAsset',
            'user',
        ],
    ],
    'frontend\\assets\\ViewRestaurantAsset' => [
        'sourcePath' => null,
        'js' => [],
        'css' => [],
        'depends' => [
            'yii\\web\\YiiAsset',
            'yii\\bootstrap\\BootstrapAsset',
            'iutbay\\yii2fontawesome\\FontAwesomeAsset',
            'viewres',
        ],
    ],
    'yii\\web\\JqueryAsset' => [
        'sourcePath' => null,
        'js' => [],
        'css' => [],
        'depends' => [
            'all',
        ],
    ],
    'yii\\web\\YiiAsset' => [
        'sourcePath' => null,
        'js' => [],
        'css' => [],
        'depends' => [
            'yii\\web\\JqueryAsset',
            'all',
        ],
    ],
    'yii\\bootstrap\\BootstrapAsset' => [
        'sourcePath' => null,
        'js' => [],
        'css' => [],
        'depends' => [
            'all',
        ],
    ],
    'iutbay\\yii2fontawesome\\FontAwesomeAsset' => [
        'sourcePath' => null,
        'css' => [
            '//maxcdn.bootstrapcdn.com/font-awesome/4.7.0/css/font-awesome.min.css',
        ],
        'basePath' => null,
        'baseUrl' => null,
        'depends' => [],
        'js' => [],
        'jsOptions' => [],
        'cssOptions' => [],
        'publishOptions' => [],
        'class' => 'iutbay\\yii2fontawesome\\FontAwesomeAsset',
    ],
];