<?php
return [
    'adminEmail' => 'support@hamstereat.my',
    'submitticket' =>  '/submitticket',
	'baseUrl' => './imageLocation',
	'submitticket-pic' => './imageLocation/submitticket/',
	'replyticket-pic' => './imageLocation/replyticket/',
	'defaultFoodImg' => './imageLocation/defaultfood.jpg',
	'defaultRestaurantImg' => './imageLocation/DefaultRestaurant.jpg',
	'foodImg' => './imageLocation/foodImg/',
	'topup' => './imageLocation/topup/',
	'userprofilepic' => './imageLocation/userprofilepic/',
	'feedback' => './imageLocation/feedback/',
	'restaurant' => './imageLocation/restaurant/',
	'sysimg' =>'./SysImg/',
	'deliveryCharge' => '5',
	'countNotic' => "",
	'countCart' => "",
	'notication' => "",
	'listOfNotic' => "",
	'langExcel'=>"C:/wamp64/www/hamsterEat/frontend/web/language/",
];
